name: project
services:
  postgres:
    image: postgres:16-alpine
    container_name: art2-database
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - art-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - art-net
  backend:
    depends_on:
      - postgres
    image: supat1400/project-backend:latest
    container_name: art2-backend
    ports:
      - ${PORT}:3000
    networks:
      - art-net
    volumes:
      - art-image:/app/dist/images
      - art-profile_picture:/app/dist/profile_picture
      - art-slips:/app/dist/slips
      - art-withdrawslips:/app/dist/withdrawslips
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
  frontend:
    depends_on:
      - backend
    image: supat1400/project-front:latest
    container_name: art2-frontend
    ports:
      - ${NGINX_PORT}:5899
    networks:
      - art-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
volumes:
  art-data:
  art-image:
  art-profile_picture:
  art-slips:
  art-withdrawslips:
networks:
  art-net:
